Repository is-tech-y24-1/Do-Svyazi.User, pull requests merged in 2022-05, with the labels that each got.

#13 feat: StyleCop configuration added
  .editorconfig
  Application/Do-Svyazi.User.Application/CQRS/Chats/Queries/GetChatById.cs
  Application/Do-Svyazi.User.Application/CQRS/Chats/Queries/GetChats.cs
  Application/Do-Svyazi.User.Application/CQRS/Users/Commands/AddUser.cs
  Application/Do-Svyazi.User.Application/CQRS/Users/Commands/ChangeUserNickNameById.cs
  Application/Do-Svyazi.User.Application/CQRS/Users/Queries/GetUsers.cs
  Application/Do-Svyazi.User.Application/Do-Svyazi.User.Application.csproj
  Application/Do-Svyazi.User.Dtos/Chats/MessengerChatDto.cs
  Application/Do-Svyazi.User.Dtos/Do-Svyazi.User.Dtos.csproj
  Application/Do-Svyazi.User.Dtos/Users/MessengerUserDto.cs
  Domain/Do-Svyazi.User.Domain/Chats/Chat.cs
  Domain/Do-Svyazi.User.Domain/Do-Svyazi.User.Domain.csproj
  Infrastructure/Do-Svyazi.User.DataAccess/Do-Svyazi.User.DataAccess.csproj
  Infrastructure/Do-Svyazi.User.Web.Api/Do-Svyazi.User.Web.Api.csproj
  Presentation/Do-Svyazi.User.Web.ApiClient/Do-Svyazi.User.Web.ApiClient.csproj
  Presentation/Do-Svyazi.User.Web.Controllers/ChatController.cs
  Presentation/Do-Svyazi.User.Web.Controllers/Do-Svyazi.User.Web.Controllers.csproj
  Presentation/Do-Svyazi.User.Web.Controllers/UserController.cs
Labels: workflow

#17 Feature/11 implement better role structure
  Domain/Do-Svyazi.User.Domain/Chats/Channel.cs
  Domain/Do-Svyazi.User.Domain/Chats/Chat.cs
  Domain/Do-Svyazi.User.Domain/Chats/GroupChat.cs
  Domain/Do-Svyazi.User.Domain/Chats/PersonalChat.cs
  Domain/Do-Svyazi.User.Domain/Chats/SavedMessages.cs
  Domain/Do-Svyazi.User.Domain/Roles/Role.cs
  Infrastructure/Do-Svyazi.User.DataAccess/UsersAndUsersAndChatDbContext.cs
Labels: domain

#20 fix: secutiry tips
  Infrastructure/Do-Svyazi.User.Web.Api/Startup.cs
Labels: bug

#21 fix: `pull-request-template.md` moved to the `.github` folder
  .github/pull_request_template.md
Labels: documentation

#18 Feature/8 implement chat entities methods
  Domain/Do-Svyazi.User.Domain/Chats/Channel.cs
  Domain/Do-Svyazi.User.Domain/Chats/Chat.cs
  Domain/Do-Svyazi.User.Domain/Chats/GroupChat.cs
  Domain/Do-Svyazi.User.Domain/Chats/PersonalChat.cs
  Domain/Do-Svyazi.User.Domain/Chats/SavedMessages.cs
  Domain/Do-Svyazi.User.Domain/Roles/Role.cs
  Domain/Do-Svyazi.User.Domain/Users/ChatUser.cs
  Domain/Do-Svyazi.User.Domain/Users/MessengerUser.cs
  Infrastructure/Do-Svyazi.User.DataAccess/UsersAndUsersAndChatDbContext.cs
  Infrastructure/Do-Svyazi.User.Web.Api/Startup.cs
Labels: domain
