Repository is-tech-y24-1/Do-Svyazi.User, pull requests merged in 2022-06, with the labels that each got.

#14 feat: Api client generation && swagger configuration
  Do-Svyazi.User.sln
  Infrastructure/Do-Svyazi.User.Web.Api/Do-Svyazi.User.Web.Api.csproj
  Infrastructure/Do-Svyazi.User.Web.Api/Startup.cs
  Infrastructure/Do-Svyazi.User.Web.Api/nswag.json
  Presentation/Do-Svyazi.User.Web.ApiClient.Backend/Do-Svyazi.User.Client.cs
  Presentation/Do-Svyazi.User.Web.ApiClient.Backend/Do-Svyazi.User.Contracts.cs
  Presentation/Do-Svyazi.User.Web.ApiClient.Backend/Do-Svyazi.User.Web.ApiClient.Backend.csproj
  Presentation/Do-Svyazi.User.Web.ApiClient.Frontend/Do-Svyazi.User.Web.ApiClient.Frontend.csproj
  Presentation/Do-Svyazi.User.Web.ApiClient.Frontend/do-svyazi.user.clients.ts
  Presentation/Do-Svyazi.User.Web.ApiClient.Frontend/package-lock.json
  Presentation/Do-Svyazi.User.Web.ApiClient.Frontend/package.json
  Presentation/Do-Svyazi.User.Web.ApiClient/Do-Svyazi.User.Web.ApiClient.csproj
Labels: architecture

#30 fix: NSwag client generation configured better
  Do-Svyazi.User.sln
  Infrastructure/Do-Svyazi.User.Web.Api/Do-Svyazi.User.Web.Api.csproj
  Presentation/Do-Svyazi.User.Web.ApiClient.Backend/Do-Svyazi.User.Web.ApiClient.Backend.csproj
  Presentation/Do-Svyazi.User.Web.ApiClient.Frontend/Do-Svyazi.User.Web.ApiClient.Frontend.csproj
  Presentation/Do-Svyazi.User.Web.ApiClient/Backend/Do-Svyazi.User.Client.cs
  Presentation/Do-Svyazi.User.Web.ApiClient/Backend/Do-Svyazi.User.Contracts.cs
  Presentation/Do-Svyazi.User.Web.ApiClient/Do-Svyazi.User.Web.ApiClient.csproj
  Presentation/Do-Svyazi.User.Web.ApiClient/Frontend/do-svyazi.user.clients.ts
  Presentation/Do-Svyazi.User.Web.ApiClient/Frontend/package-lock.json
  Presentation/Do-Svyazi.User.Web.ApiClient/Frontend/package.json
  Presentation/Do-Svyazi.User.Web.ApiClient/nswag.json
Labels: architecture

#33 Create LICENSE
  LICENSE
Labels: documentation

#29 feat/ CRUD for Roles
  Application/Do-Svyazi.User.Application/CQRS/Roles/Commands/ChangeUserRoleInChat.cs
  Application/Do-Svyazi.User.Application/CQRS/Roles/Commands/CreateRoleForChat.cs
  Application/Do-Svyazi.User.Application/CQRS/Roles/Queries/GetRoleByUserId.cs
  Application/Do-Svyazi.User.Application/DbContexts/IDbContext.cs
  Application/Do-Svyazi.User.Dtos/Do-Svyazi.User.Dtos.csproj
  Application/Do-Svyazi.User.Dtos/Roles/ChatAndUserId.cs
  Application/Do-Svyazi.User.Dtos/Roles/RoleDto.cs
  Infrastructure/Do-Svyazi.User.DataAccess/DoSvaziDbContext.cs
  Presentation/Do-Svyazi.User.Web.Controllers/RolesController.cs
Labels: api

#42 Chore/packages publishing
  .github/workflows/npm-packages.yml
  .github/workflows/nuget-packages.yml
  Infrastructure/Do-Svyazi.User.Web.Api/nswag.json
  Presentation/Do-Svyazi.User.Web.ApiClient/Do-Svyazi.User.Web.ApiClient.csproj
  Presentation/Do-Svyazi.User.Web.ApiClient/Frontend/package-lock.json
  Presentation/Do-Svyazi.User.Web.ApiClient/Frontend/package.json
  Presentation/Do-Svyazi.User.Web.ApiClient/nswag.json
  Presentation/Do-Svyazi.User.Web.ApiClient/openApiContracts.json
  Presentation/Do-Svyazi.User.Web.ApiClient/package-lock.json
  Presentation/Do-Svyazi.User.Web.ApiClient/package.json
Labels: documentation, api

#44 chore: docs folder created
  Docs/CONTRIBUTING.md
  Docs/LICENSE
Labels: documentation
